use super::*;

#[derive(Serialize)]
pub(super) struct CorePlayerStatsSnapshot {
    pub(super) score: i32,
    pub(super) goals: i32,
    pub(super) assists: i32,
    pub(super) saves: i32,
    pub(super) shots: i32,
    pub(super) goals_conceded_while_last_defender: u32,
    pub(super) goals_for_while_most_back: u32,
    pub(super) goals_against_while_most_back: u32,
    pub(super) goal_against_boost_sample_count: u32,
    pub(super) cumulative_boost_on_goals_against: f32,
    pub(super) average_boost_on_goals_against: f32,
    pub(super) last_boost_on_goal_against: Option<f32>,
    pub(super) goal_against_boost_leadup_sample_count: u32,
    pub(super) cumulative_average_boost_in_goal_against_leadup: f32,
    pub(super) cumulative_min_boost_in_goal_against_leadup: f32,
    pub(super) average_boost_in_goal_against_leadup: f32,
    pub(super) average_min_boost_in_goal_against_leadup: f32,
    pub(super) last_average_boost_in_goal_against_leadup: Option<f32>,
    pub(super) last_min_boost_in_goal_against_leadup: Option<f32>,
    pub(super) goal_against_position_sample_count: u32,
    pub(super) cumulative_goal_against_position_x: f32,
    pub(super) cumulative_goal_against_position_y: f32,
    pub(super) cumulative_goal_against_position_z: f32,
    pub(super) average_goal_against_position_x: f32,
    pub(super) average_goal_against_position_y: f32,
    pub(super) average_goal_against_position_z: f32,
    pub(super) last_goal_against_position: Option<GoalContextPosition>,
    pub(super) scoring_goal_last_touch_position_sample_count: u32,
    pub(super) cumulative_scoring_goal_last_touch_position_x: f32,
    pub(super) cumulative_scoring_goal_last_touch_position_y: f32,
    pub(super) cumulative_scoring_goal_last_touch_position_z: f32,
    pub(super) average_scoring_goal_last_touch_position_x: f32,
    pub(super) average_scoring_goal_last_touch_position_y: f32,
    pub(super) average_scoring_goal_last_touch_position_z: f32,
    pub(super) last_scoring_goal_last_touch_position: Option<GoalContextPosition>,
    pub(super) kickoff_goal_count: u32,
    pub(super) short_goal_count: u32,
    pub(super) medium_goal_count: u32,
    pub(super) long_goal_count: u32,
    pub(super) goal_times: Vec<f32>,
    pub(super) goal_ball_air_time_sample_count: u32,
    pub(super) cumulative_goal_ball_air_time: f32,
    pub(super) average_goal_ball_air_time: f32,
    pub(super) median_goal_ball_air_time: f32,
    pub(super) last_goal_ball_air_time: Option<f32>,
    pub(super) goal_ball_air_times: Vec<f32>,
    pub(super) counter_attack_goal_count: u32,
    pub(super) sustained_pressure_goal_count: u32,
    pub(super) other_buildup_goal_count: u32,
}
