use super::playback_config_value_goals::goal_value;
use super::*;

pub(super) fn extra_goal_values(config: &Map<String, Value>) -> Vec<(&'static str, f64)> {
    vec![
        goal_value(
            config,
            "flick_goal",
            "flick_goal_max_event_to_goal_seconds",
            FlickGoalCalculatorConfig::default().max_event_to_goal_seconds,
        ),
        goal_value(
            config,
            "double_tap_goal",
            "double_tap_goal_max_event_to_goal_seconds",
            DoubleTapGoalCalculatorConfig::default().max_event_to_goal_seconds,
        ),
        goal_value(
            config,
            "one_timer_goal",
            "one_timer_goal_max_event_to_goal_seconds",
            OneTimerGoalCalculatorConfig::default().max_event_to_goal_seconds,
        ),
        goal_value(
            config,
            "air_dribble_goal",
            "air_dribble_goal_max_end_to_goal_seconds",
            AirDribbleGoalCalculatorConfig::default().max_end_to_goal_seconds,
        ),
        goal_value(
            config,
            "flip_reset_goal",
            "flip_reset_goal_max_event_to_goal_seconds",
            FlipResetGoalCalculatorConfig::default().max_event_to_goal_seconds,
        ),
        goal_value(
            config,
            "half_volley",
            "half_volley_max_bounce_to_touch_seconds",
            HalfVolleyCalculatorConfig::default().max_bounce_to_touch_seconds,
        ),
        goal_value(
            config,
            "half_volley",
            "half_volley_min_ball_speed",
            HalfVolleyCalculatorConfig::default().min_ball_speed,
        ),
        goal_value(
            config,
            "half_volley_goal",
            "half_volley_goal_max_touch_to_goal_seconds",
            HalfVolleyGoalCalculatorConfig::default().max_touch_to_goal_seconds,
        ),
        goal_value(
            config,
            "half_volley_goal",
            "half_volley_goal_min_goal_alignment",
            HalfVolleyGoalCalculatorConfig::default().min_goal_alignment,
        ),
    ]
}
