pub(in crate::collector::stats::playback) const CUMULATIVE_AVERAGE_FIELDS: [(&str, &str, &str);
    10] = [
    (
        "cumulative_boost_on_goals_against",
        "average_boost_on_goals_against",
        "goal_against_boost_sample_count",
    ),
    (
        "cumulative_average_boost_in_goal_against_leadup",
        "average_boost_in_goal_against_leadup",
        "goal_against_boost_leadup_sample_count",
    ),
    (
        "cumulative_min_boost_in_goal_against_leadup",
        "average_min_boost_in_goal_against_leadup",
        "goal_against_boost_leadup_sample_count",
    ),
    (
        "cumulative_goal_against_position_x",
        "average_goal_against_position_x",
        "goal_against_position_sample_count",
    ),
    (
        "cumulative_goal_against_position_y",
        "average_goal_against_position_y",
        "goal_against_position_sample_count",
    ),
    (
        "cumulative_goal_against_position_z",
        "average_goal_against_position_z",
        "goal_against_position_sample_count",
    ),
    (
        "cumulative_scoring_goal_last_touch_position_x",
        "average_scoring_goal_last_touch_position_x",
        "scoring_goal_last_touch_position_sample_count",
    ),
    (
        "cumulative_scoring_goal_last_touch_position_y",
        "average_scoring_goal_last_touch_position_y",
        "scoring_goal_last_touch_position_sample_count",
    ),
    (
        "cumulative_scoring_goal_last_touch_position_z",
        "average_scoring_goal_last_touch_position_z",
        "scoring_goal_last_touch_position_sample_count",
    ),
    (
        "cumulative_goal_ball_air_time",
        "average_goal_ball_air_time",
        "goal_ball_air_time_sample_count",
    ),
];
