import type { BallData as GeneratedBallData } from "./generated/BallData.ts";
import type { BallFrame as GeneratedBallFrame } from "./generated/BallFrame.ts";
import type { BoostPadEvent as GeneratedBoostPadEvent } from "./generated/BoostPadEvent.ts";
import type { DemolishInfo as GeneratedDemolishInfo } from "./generated/DemolishInfo.ts";
import type { GoalEvent as GeneratedGoalEvent } from "./generated/GoalEvent.ts";
import type { MetadataFrame as GeneratedMetadataFrame } from "./generated/MetadataFrame.ts";
import type { PlayerData as GeneratedPlayerData } from "./generated/PlayerData.ts";
import type { PlayerFrame as GeneratedPlayerFrame } from "./generated/PlayerFrame.ts";
import type { PlayerInfo as GeneratedPlayerInfo } from "./generated/PlayerInfo.ts";
import type { PlayerStatEvent as GeneratedPlayerStatEvent } from "./generated/PlayerStatEvent.ts";
import type { PlayerStatEventKind as GeneratedPlayerStatEventKind } from "./generated/PlayerStatEventKind.ts";
import type { QuaternionTs as GeneratedQuaternionTs } from "./generated/QuaternionTs.ts";
import type { RemoteIdTs as GeneratedRemoteIdTs } from "./generated/RemoteIdTs.ts";
import type { ReplayData as GeneratedReplayData } from "./generated/ReplayData.ts";
import type { ResolvedBoostPad as GeneratedResolvedBoostPad } from "./generated/ResolvedBoostPad.ts";
import type { RigidBodyTs as GeneratedRigidBodyTs } from "./generated/RigidBodyTs.ts";
import type { Vector3fTs as GeneratedVector3fTs } from "./generated/Vector3fTs.ts";

export type RawVec3 = GeneratedVector3fTs;
export type RawRotation = GeneratedQuaternionTs;
export type RawRigidBody = GeneratedRigidBodyTs;
export type RawBallFrame = GeneratedBallFrame;
export type RawBallFrameData = Exclude<GeneratedBallFrame, "Empty">["Data"];
export type RawPlayerFrame = GeneratedPlayerFrame;
export type RawPlayerFrameData = Exclude<GeneratedPlayerFrame, "Empty">["Data"];
export type RawPlayerData = GeneratedPlayerData;
export type RawBallData = GeneratedBallData;
export type RawMetadataFrame = GeneratedMetadataFrame;
export type RawPlayerId = GeneratedRemoteIdTs;
export type RawPlayerInfo = GeneratedPlayerInfo;
export type RawPlayerStatEventKind = GeneratedPlayerStatEventKind;
export type RawDemolishInfo = GeneratedDemolishInfo;
export type RawGoalEvent = GeneratedGoalEvent;
export type RawPlayerStatEvent = GeneratedPlayerStatEvent;
export type RawBoostPadEvent = GeneratedBoostPadEvent;
export type RawBoostPad = GeneratedResolvedBoostPad;
export type RawReplayFramesData = GeneratedReplayData;
