use crate::*;

use super::*;

impl StatFieldProvider for BoostStats {
    fn visit_stat_fields(&self, visitor: &mut dyn FnMut(ExportedStat)) {
        visitor(ExportedStat::float(
            "boost",
            "bpm",
            StatUnit::BoostPerMinute,
            self.bpm(),
        ));
        visitor(ExportedStat::float(
            "boost",
            "avg_amount",
            StatUnit::Boost,
            self.average_boost_amount(),
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_collected",
            StatUnit::Boost,
            self.amount_collected,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_stolen",
            StatUnit::Boost,
            self.amount_stolen,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_collected_big",
            StatUnit::Boost,
            self.amount_collected_big,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_stolen_big",
            StatUnit::Boost,
            self.amount_stolen_big,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_collected_small",
            StatUnit::Boost,
            self.amount_collected_small,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_stolen_small",
            StatUnit::Boost,
            self.amount_stolen_small,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_respawned",
            StatUnit::Boost,
            self.amount_respawned,
        ));
        visitor(ExportedStat::unsigned(
            "boost",
            "count_collected_big",
            StatUnit::Count,
            self.big_pads_collected,
        ));
        visitor(ExportedStat::unsigned(
            "boost",
            "count_stolen_big",
            StatUnit::Count,
            self.big_pads_stolen,
        ));
        visitor(ExportedStat::unsigned(
            "boost",
            "count_collected_small",
            StatUnit::Count,
            self.small_pads_collected,
        ));
        visitor(ExportedStat::unsigned(
            "boost",
            "count_stolen_small",
            StatUnit::Count,
            self.small_pads_stolen,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_overfill",
            StatUnit::Boost,
            self.overfill_total,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_overfill_stolen",
            StatUnit::Boost,
            self.overfill_from_stolen,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_used",
            StatUnit::Boost,
            self.amount_used,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_used_while_grounded",
            StatUnit::Boost,
            self.amount_used_while_grounded,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_used_while_airborne",
            StatUnit::Boost,
            self.amount_used_while_airborne,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_used_while_supersonic",
            StatUnit::Boost,
            self.amount_used_while_supersonic,
        ));
        visitor(ExportedStat::float(
            "boost",
            "time_zero_boost",
            StatUnit::Seconds,
            self.time_zero_boost,
        ));
        visitor(ExportedStat::float(
            "boost",
            "time_full_boost",
            StatUnit::Seconds,
            self.time_hundred_boost,
        ));
        visitor(ExportedStat::float(
            "boost",
            "time_boost_0_25",
            StatUnit::Seconds,
            self.time_boost_0_25,
        ));
        visitor(ExportedStat::float(
            "boost",
            "time_boost_25_50",
            StatUnit::Seconds,
            self.time_boost_25_50,
        ));
        visitor(ExportedStat::float(
            "boost",
            "time_boost_50_75",
            StatUnit::Seconds,
            self.time_boost_50_75,
        ));
        visitor(ExportedStat::float(
            "boost",
            "time_boost_75_100",
            StatUnit::Seconds,
            self.time_boost_75_100,
        ));
        visitor(ExportedStat::float(
            "boost",
            "percent_zero_boost",
            StatUnit::Percent,
            self.zero_boost_pct(),
        ));
        visitor(ExportedStat::float(
            "boost",
            "percent_full_boost",
            StatUnit::Percent,
            self.hundred_boost_pct(),
        ));
        visitor(ExportedStat::float(
            "boost",
            "percent_boost_0_25",
            StatUnit::Percent,
            self.boost_0_25_pct(),
        ));
        visitor(ExportedStat::float(
            "boost",
            "percent_boost_25_50",
            StatUnit::Percent,
            self.boost_25_50_pct(),
        ));
        visitor(ExportedStat::float(
            "boost",
            "percent_boost_50_75",
            StatUnit::Percent,
            self.boost_50_75_pct(),
        ));
        visitor(ExportedStat::float(
            "boost",
            "percent_boost_75_100",
            StatUnit::Percent,
            self.boost_75_100_pct(),
        ));
    }
}
