use super::*;

impl BoostStats {
    pub(super) fn visit_collection_stat_fields(&self, visitor: &mut dyn FnMut(ExportedStat)) {
        visitor(ExportedStat::float(
            "boost",
            "bpm",
            StatUnit::BoostPerMinute,
            self.bpm(),
        ));
        visitor(ExportedStat::float(
            "boost",
            "avg_amount",
            StatUnit::Boost,
            self.average_boost_amount(),
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_collected",
            StatUnit::Boost,
            self.amount_collected,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_collected_inactive",
            StatUnit::Boost,
            self.amount_collected_inactive,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_stolen",
            StatUnit::Boost,
            self.amount_stolen,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_collected_big",
            StatUnit::Boost,
            self.amount_collected_big,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_stolen_big",
            StatUnit::Boost,
            self.amount_stolen_big,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_collected_small",
            StatUnit::Boost,
            self.amount_collected_small,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_stolen_small",
            StatUnit::Boost,
            self.amount_stolen_small,
        ));
        visitor(ExportedStat::float(
            "boost",
            "amount_respawned",
            StatUnit::Boost,
            self.amount_respawned,
        ));
    }
}
