use super::*;

impl BoostStats {
    pub(super) fn visit_time_stat_fields(&self, visitor: &mut dyn FnMut(ExportedStat)) {
        visitor(ExportedStat::float(
            "boost",
            "time_zero_boost",
            StatUnit::Seconds,
            self.time_zero_boost,
        ));
        visitor(ExportedStat::float(
            "boost",
            "time_full_boost",
            StatUnit::Seconds,
            self.time_hundred_boost,
        ));
        visitor(ExportedStat::float(
            "boost",
            "time_boost_0_25",
            StatUnit::Seconds,
            self.time_boost_0_25,
        ));
        visitor(ExportedStat::float(
            "boost",
            "time_boost_25_50",
            StatUnit::Seconds,
            self.time_boost_25_50,
        ));
        visitor(ExportedStat::float(
            "boost",
            "time_boost_50_75",
            StatUnit::Seconds,
            self.time_boost_50_75,
        ));
        visitor(ExportedStat::float(
            "boost",
            "time_boost_75_100",
            StatUnit::Seconds,
            self.time_boost_75_100,
        ));
        visitor(ExportedStat::float(
            "boost",
            "percent_zero_boost",
            StatUnit::Percent,
            self.zero_boost_pct(),
        ));
        visitor(ExportedStat::float(
            "boost",
            "percent_full_boost",
            StatUnit::Percent,
            self.hundred_boost_pct(),
        ));
        visitor(ExportedStat::float(
            "boost",
            "percent_boost_0_25",
            StatUnit::Percent,
            self.boost_0_25_pct(),
        ));
        visitor(ExportedStat::float(
            "boost",
            "percent_boost_25_50",
            StatUnit::Percent,
            self.boost_25_50_pct(),
        ));
        visitor(ExportedStat::float(
            "boost",
            "percent_boost_50_75",
            StatUnit::Percent,
            self.boost_50_75_pct(),
        ));
        visitor(ExportedStat::float(
            "boost",
            "percent_boost_75_100",
            StatUnit::Percent,
            self.boost_75_100_pct(),
        ));
    }
}
