use crate::*;

use super::*;

impl StatFieldProvider for FiftyFiftyStats {
    fn visit_stat_fields(&self, visitor: &mut dyn FnMut(ExportedStat)) {
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "count",
            StatUnit::Count,
            self.count,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "team_zero_wins",
            StatUnit::Count,
            self.team_zero_wins,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "team_one_wins",
            StatUnit::Count,
            self.team_one_wins,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "neutral_outcomes",
            StatUnit::Count,
            self.neutral_outcomes,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "kickoff_count",
            StatUnit::Count,
            self.kickoff_count,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "kickoff_team_zero_wins",
            StatUnit::Count,
            self.kickoff_team_zero_wins,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "kickoff_team_one_wins",
            StatUnit::Count,
            self.kickoff_team_one_wins,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "kickoff_neutral_outcomes",
            StatUnit::Count,
            self.kickoff_neutral_outcomes,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "team_zero_possession_after_count",
            StatUnit::Count,
            self.team_zero_possession_after_count,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "team_one_possession_after_count",
            StatUnit::Count,
            self.team_one_possession_after_count,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "neutral_possession_after_count",
            StatUnit::Count,
            self.neutral_possession_after_count,
        ));
        visitor(ExportedStat::float(
            "fifty_fifty",
            "team_zero_win_pct",
            StatUnit::Percent,
            self.team_zero_win_pct(),
        ));
        visitor(ExportedStat::float(
            "fifty_fifty",
            "team_one_win_pct",
            StatUnit::Percent,
            self.team_one_win_pct(),
        ));
        visitor(ExportedStat::float(
            "fifty_fifty",
            "kickoff_team_zero_win_pct",
            StatUnit::Percent,
            self.kickoff_team_zero_win_pct(),
        ));
        visitor(ExportedStat::float(
            "fifty_fifty",
            "kickoff_team_one_win_pct",
            StatUnit::Percent,
            self.kickoff_team_one_win_pct(),
        ));
    }
}

impl StatFieldProvider for FiftyFiftyPlayerStats {
    fn visit_stat_fields(&self, visitor: &mut dyn FnMut(ExportedStat)) {
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "count",
            StatUnit::Count,
            self.count,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "wins",
            StatUnit::Count,
            self.wins,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "losses",
            StatUnit::Count,
            self.losses,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "neutral_outcomes",
            StatUnit::Count,
            self.neutral_outcomes,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "kickoff_count",
            StatUnit::Count,
            self.kickoff_count,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "kickoff_wins",
            StatUnit::Count,
            self.kickoff_wins,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "kickoff_losses",
            StatUnit::Count,
            self.kickoff_losses,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "kickoff_neutral_outcomes",
            StatUnit::Count,
            self.kickoff_neutral_outcomes,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "possession_after_count",
            StatUnit::Count,
            self.possession_after_count,
        ));
        visitor(ExportedStat::unsigned(
            "fifty_fifty",
            "kickoff_possession_after_count",
            StatUnit::Count,
            self.kickoff_possession_after_count,
        ));
        visitor(ExportedStat::float(
            "fifty_fifty",
            "win_pct",
            StatUnit::Percent,
            self.win_pct(),
        ));
        visitor(ExportedStat::float(
            "fifty_fifty",
            "kickoff_win_pct",
            StatUnit::Percent,
            self.kickoff_win_pct(),
        ));
    }
}
