use super::*;

pub(super) fn visit_team_count_fields(
    stats: &FiftyFiftyStats,
    visitor: &mut dyn FnMut(ExportedStat),
) {
    visitor(ExportedStat::unsigned(
        "fifty_fifty",
        "count",
        StatUnit::Count,
        stats.count,
    ));
    visitor(ExportedStat::unsigned(
        "fifty_fifty",
        "team_zero_wins",
        StatUnit::Count,
        stats.team_zero_wins,
    ));
    visitor(ExportedStat::unsigned(
        "fifty_fifty",
        "team_one_wins",
        StatUnit::Count,
        stats.team_one_wins,
    ));
    visitor(ExportedStat::unsigned(
        "fifty_fifty",
        "neutral_outcomes",
        StatUnit::Count,
        stats.neutral_outcomes,
    ));
    visitor(ExportedStat::unsigned(
        "fifty_fifty",
        "kickoff_count",
        StatUnit::Count,
        stats.kickoff_count,
    ));
    visitor(ExportedStat::unsigned(
        "fifty_fifty",
        "kickoff_team_zero_wins",
        StatUnit::Count,
        stats.kickoff_team_zero_wins,
    ));
    visitor(ExportedStat::unsigned(
        "fifty_fifty",
        "kickoff_team_one_wins",
        StatUnit::Count,
        stats.kickoff_team_one_wins,
    ));
    visitor(ExportedStat::unsigned(
        "fifty_fifty",
        "kickoff_neutral_outcomes",
        StatUnit::Count,
        stats.kickoff_neutral_outcomes,
    ));
    visitor(ExportedStat::unsigned(
        "fifty_fifty",
        "team_zero_possession_after_count",
        StatUnit::Count,
        stats.team_zero_possession_after_count,
    ));
    visitor(ExportedStat::unsigned(
        "fifty_fifty",
        "team_one_possession_after_count",
        StatUnit::Count,
        stats.team_one_possession_after_count,
    ));
    visitor(ExportedStat::unsigned(
        "fifty_fifty",
        "neutral_possession_after_count",
        StatUnit::Count,
        stats.neutral_possession_after_count,
    ));
}
