mod air_dribble;
mod backboard;
mod ball_carry;
mod boost;
mod bump;
mod ceiling_shot;
mod center;
mod core;
mod demo;
mod dodge_reset;
mod double_tap;
mod exported_stat;
mod fifty_fifty;
mod flick;
mod half_flip;
mod half_volley;
mod labeled_counts;
mod labeled_float_sums;
mod movement;
mod musty_flick;
mod one_timer;
mod pass;
mod positioning;
mod possession;
mod powerslide;
mod pressure;
mod rotation;
mod rush;
mod speed_flip;
mod stat_descriptor;
mod stat_label;
mod stat_value;
mod territorial_pressure;
mod touch;
mod wall_aerial;
mod wall_aerial_shot;
mod wavedash;
mod whiff;

pub use exported_stat::{ExportedStat, StatFieldProvider};
pub use labeled_counts::{LabeledCountEntry, LabeledCounts};
pub use labeled_float_sums::{LabeledFloatSumEntry, LabeledFloatSums};
pub use stat_descriptor::StatDescriptor;
use stat_label::leak_string;
pub use stat_label::{StatLabel, StatUnit};
pub use stat_value::StatValue;

pub const LEGACY_STAT_VARIANT: &str = "legacy";
pub const LABELED_STAT_VARIANT: &str = "labeled";
