use super::*;

impl PositioningStats {
    pub(super) fn visit_positioning_percent_stat_fields(
        &self,
        visitor: &mut dyn FnMut(ExportedStat),
    ) {
        visitor(ExportedStat::float(
            "positioning",
            "percent_defensive_third",
            StatUnit::Percent,
            self.defensive_third_pct(),
        ));
        visitor(ExportedStat::float(
            "positioning",
            "percent_neutral_third",
            StatUnit::Percent,
            self.neutral_third_pct(),
        ));
        visitor(ExportedStat::float(
            "positioning",
            "percent_offensive_third",
            StatUnit::Percent,
            self.offensive_third_pct(),
        ));
        visitor(ExportedStat::float(
            "positioning",
            "percent_defensive_half",
            StatUnit::Percent,
            self.defensive_half_pct(),
        ));
        visitor(ExportedStat::float(
            "positioning",
            "percent_offensive_half",
            StatUnit::Percent,
            self.offensive_half_pct(),
        ));
        visitor(ExportedStat::float(
            "positioning",
            "percent_behind_ball",
            StatUnit::Percent,
            self.behind_ball_pct(),
        ));
        visitor(ExportedStat::float(
            "positioning",
            "percent_level_with_ball",
            StatUnit::Percent,
            self.level_with_ball_pct(),
        ));
        visitor(ExportedStat::float(
            "positioning",
            "percent_in_front_of_ball",
            StatUnit::Percent,
            self.in_front_of_ball_pct(),
        ));
        visitor(ExportedStat::float(
            "positioning",
            "percent_most_back",
            StatUnit::Percent,
            self.most_back_pct(),
        ));
        visitor(ExportedStat::float(
            "positioning",
            "percent_most_forward",
            StatUnit::Percent,
            self.most_forward_pct(),
        ));
        visitor(ExportedStat::float(
            "positioning",
            "percent_mid_role",
            StatUnit::Percent,
            self.mid_role_pct(),
        ));
        visitor(ExportedStat::float(
            "positioning",
            "percent_other_role",
            StatUnit::Percent,
            self.other_role_pct(),
        ));
        visitor(ExportedStat::float(
            "positioning",
            "percent_closest_to_ball",
            StatUnit::Percent,
            self.closest_to_ball_pct(),
        ));
        visitor(ExportedStat::float(
            "positioning",
            "percent_farthest_from_ball",
            StatUnit::Percent,
            self.farthest_from_ball_pct(),
        ));
    }
}
