use super::*;

impl PositioningStats {
    pub(super) fn visit_positioning_time_stat_fields(&self, visitor: &mut dyn FnMut(ExportedStat)) {
        visitor(ExportedStat::float(
            "positioning",
            "time_defensive_third",
            StatUnit::Seconds,
            self.time_defensive_zone,
        ));
        visitor(ExportedStat::float(
            "positioning",
            "time_neutral_third",
            StatUnit::Seconds,
            self.time_neutral_zone,
        ));
        visitor(ExportedStat::float(
            "positioning",
            "time_offensive_third",
            StatUnit::Seconds,
            self.time_offensive_zone,
        ));
        visitor(ExportedStat::float(
            "positioning",
            "time_defensive_half",
            StatUnit::Seconds,
            self.time_defensive_half,
        ));
        visitor(ExportedStat::float(
            "positioning",
            "time_offensive_half",
            StatUnit::Seconds,
            self.time_offensive_half,
        ));
        visitor(ExportedStat::float(
            "positioning",
            "time_behind_ball",
            StatUnit::Seconds,
            self.time_behind_ball,
        ));
        visitor(ExportedStat::float(
            "positioning",
            "time_level_with_ball",
            StatUnit::Seconds,
            self.time_level_with_ball,
        ));
        visitor(ExportedStat::float(
            "positioning",
            "time_in_front_of_ball",
            StatUnit::Seconds,
            self.time_in_front_of_ball,
        ));
        visitor(ExportedStat::float(
            "positioning",
            "time_demolished",
            StatUnit::Seconds,
            self.time_demolished,
        ));
    }
}
