use crate::*;

use super::*;

impl StatFieldProvider for TerritorialPressureStats {
    fn visit_stat_fields(&self, visitor: &mut dyn FnMut(ExportedStat)) {
        visitor(ExportedStat::float(
            "territorial_pressure",
            "tracked_time",
            StatUnit::Seconds,
            self.tracked_time,
        ));
        visitor(ExportedStat::unsigned(
            "territorial_pressure",
            "team_zero_session_count",
            StatUnit::Count,
            self.team_zero_session_count,
        ));
        visitor(ExportedStat::unsigned(
            "territorial_pressure",
            "team_one_session_count",
            StatUnit::Count,
            self.team_one_session_count,
        ));
        visitor(ExportedStat::float(
            "territorial_pressure",
            "team_zero_session_time",
            StatUnit::Seconds,
            self.team_zero_session_time,
        ));
        visitor(ExportedStat::float(
            "territorial_pressure",
            "team_one_session_time",
            StatUnit::Seconds,
            self.team_one_session_time,
        ));
        visitor(ExportedStat::float(
            "territorial_pressure",
            "team_zero_offensive_half_time",
            StatUnit::Seconds,
            self.team_zero_offensive_half_time,
        ));
        visitor(ExportedStat::float(
            "territorial_pressure",
            "team_one_offensive_half_time",
            StatUnit::Seconds,
            self.team_one_offensive_half_time,
        ));
        visitor(ExportedStat::float(
            "territorial_pressure",
            "team_zero_offensive_third_time",
            StatUnit::Seconds,
            self.team_zero_offensive_third_time,
        ));
        visitor(ExportedStat::float(
            "territorial_pressure",
            "team_one_offensive_third_time",
            StatUnit::Seconds,
            self.team_one_offensive_third_time,
        ));
        visitor(ExportedStat::float(
            "territorial_pressure",
            "team_zero_longest_session_time",
            StatUnit::Seconds,
            self.team_zero_longest_session_time,
        ));
        visitor(ExportedStat::float(
            "territorial_pressure",
            "team_one_longest_session_time",
            StatUnit::Seconds,
            self.team_one_longest_session_time,
        ));
        for entry in &self.labeled_session_counts.entries {
            visitor(ExportedStat::unsigned_labeled(
                "territorial_pressure",
                "session_count",
                StatUnit::Count,
                entry.labels.clone(),
                entry.count,
            ));
        }
        for entry in &self.labeled_time.entries {
            visitor(ExportedStat::float_labeled(
                "territorial_pressure",
                "session_time",
                StatUnit::Seconds,
                entry.labels.clone(),
                entry.value,
            ));
        }
    }
}
