use serde::Serialize;

#[derive(Debug, Clone, PartialEq, Serialize, ts_rs::TS)]
#[ts(export)]
pub struct StatsTimelineConfig {
    pub most_back_forward_threshold_y: f32,
    pub level_ball_depth_margin: f32,
    pub pressure_neutral_zone_half_width_y: f32,
    pub territorial_pressure_neutral_zone_half_width_y: f32,
    pub territorial_pressure_min_establish_seconds: f32,
    pub territorial_pressure_min_establish_third_seconds: f32,
    pub territorial_pressure_relief_grace_seconds: f32,
    pub territorial_pressure_confirmed_relief_grace_seconds: f32,
    pub rotation_role_depth_margin: f32,
    pub rotation_first_man_ambiguity_margin: f32,
    pub rotation_first_man_debounce_seconds: f32,
    pub rush_max_start_y: f32,
    pub rush_attack_support_distance_y: f32,
    pub rush_defender_distance_y: f32,
    pub rush_min_possession_retained_seconds: f32,
    pub aerial_goal_min_ball_z: f32,
    pub high_aerial_goal_min_ball_z: f32,
    pub long_distance_goal_max_attacking_y: f32,
    pub own_half_goal_max_attacking_y: f32,
    pub empty_net_min_defender_y_margin: f32,
    pub empty_net_min_defender_distance: f32,
    pub empty_net_max_touch_attacking_y: f32,
    pub flick_goal_max_event_to_goal_seconds: f32,
    pub double_tap_goal_max_event_to_goal_seconds: f32,
    pub one_timer_goal_max_event_to_goal_seconds: f32,
    pub air_dribble_goal_max_end_to_goal_seconds: f32,
    pub flip_reset_goal_max_event_to_goal_seconds: f32,
    pub half_volley_max_bounce_to_touch_seconds: f32,
    pub half_volley_min_ball_speed: f32,
    pub half_volley_goal_max_touch_to_goal_seconds: f32,
    pub half_volley_goal_min_goal_alignment: f32,
}
