use serde::Serialize;

use crate::*;

#[derive(Debug, Clone, Default, PartialEq, Serialize, ts_rs::TS)]
#[ts(export)]
pub struct ReplayStatsTimelineEvents {
    pub timeline: Vec<TimelineEvent>,
    pub core_player: Vec<CorePlayerStatsEvent>,
    pub core_team: Vec<CoreTeamStatsEvent>,
    pub possession: Vec<PossessionEvent>,
    pub pressure: Vec<PressureEvent>,
    pub territorial_pressure: Vec<TerritorialPressureEvent>,
    pub movement: Vec<MovementEvent>,
    pub positioning: Vec<PositioningEvent>,
    pub rotation_player: Vec<RotationPlayerEvent>,
    pub rotation_team: Vec<RotationTeamEvent>,
    pub mechanics: Vec<MechanicEvent>,
    pub goal_context: Vec<GoalContextEvent>,
    pub backboard: Vec<BackboardBounceEvent>,
    pub ceiling_shot: Vec<CeilingShotEvent>,
    pub wall_aerial: Vec<WallAerialEvent>,
    pub wall_aerial_shot: Vec<WallAerialShotEvent>,
    pub center: Vec<CenterEvent>,
    pub flick: Vec<FlickEvent>,
    pub musty_flick: Vec<MustyFlickEvent>,
    pub dodge_reset: Vec<DodgeResetEvent>,
    pub double_tap: Vec<DoubleTapEvent>,
    pub fifty_fifty: Vec<FiftyFiftyEvent>,
    pub one_timer: Vec<OneTimerEvent>,
    pub pass: Vec<PassEvent>,
    pub pass_last_completed: Vec<PassLastCompletedEvent>,
    pub ball_carry: Vec<BallCarryEvent>,
    pub goal_tags: Vec<GoalTagEvent>,
    pub rush: Vec<RushEvent>,
    pub speed_flip: Vec<SpeedFlipEvent>,
    pub half_flip: Vec<HalfFlipEvent>,
    pub half_volley: Vec<HalfVolleyEvent>,
    pub wavedash: Vec<WavedashEvent>,
    pub whiff: Vec<WhiffEvent>,
    pub powerslide: Vec<PowerslideEvent>,
    pub touch: Vec<TouchStatsEvent>,
    pub touch_ball_movement: Vec<TouchBallMovementEvent>,
    pub touch_last_touch: Vec<TouchLastTouchEvent>,
    pub boost_pickups: Vec<BoostPickupComparisonEvent>,
    pub boost_ledger: Vec<BoostLedgerEvent>,
    pub boost_state: Vec<BoostStateEvent>,
    pub bump: Vec<BumpEvent>,
}
