use super::*;

pub(super) const GOAL_AFTER_KICKOFF_BUCKET_KICKOFF_MAX_SECONDS: f32 = 10.0;
pub(super) const GOAL_AFTER_KICKOFF_BUCKET_SHORT_MAX_SECONDS: f32 = 20.0;
pub(super) const GOAL_AFTER_KICKOFF_BUCKET_MEDIUM_MAX_SECONDS: f32 = 40.0;
pub(super) const GOAL_BUILDUP_LOOKBACK_SECONDS: f32 = 12.0;
pub(super) const COUNTER_ATTACK_MAX_ATTACK_SECONDS: f32 = 4.0;
pub(super) const COUNTER_ATTACK_MIN_DEFENSIVE_HALF_SECONDS: f32 = 4.0;
pub(super) const COUNTER_ATTACK_MIN_DEFENSIVE_THIRD_SECONDS: f32 = 1.0;
pub(super) const SUSTAINED_PRESSURE_MIN_ATTACK_SECONDS: f32 = 6.0;
pub(super) const SUSTAINED_PRESSURE_MIN_OFFENSIVE_HALF_SECONDS: f32 = 7.0;
pub(super) const SUSTAINED_PRESSURE_MIN_OFFENSIVE_THIRD_SECONDS: f32 = 3.5;
pub(super) const GOAL_CONTEXT_BOOST_LEADUP_SECONDS: f32 = 5.0;
pub(super) const BALL_GROUND_CONTACT_MAX_Z: f32 = BALL_RADIUS_Z + 5.0;
