use super::*;

pub struct ReplayProcessor<'a> {
    pub replay: &'a boxcars::Replay,
    pub(crate) spatial_normalization_factor: f32,
    pub(crate) rigid_body_velocity_normalization_factor: f32,
    pub(crate) uses_legacy_rigid_body_rotation: bool,
    pub(crate) cached_object_ids: CachedObjectIds,
    pub(crate) is_boost_pad_object: Vec<bool>,
    pub actor_state: ActorStateModeler,
    pub object_id_to_name: HashMap<boxcars::ObjectId, String>,
    pub name_to_object_id: HashMap<String, boxcars::ObjectId>,
    pub ball_actor_id: Option<boxcars::ActorId>,
    pub team_zero: Vec<PlayerId>,
    pub team_one: Vec<PlayerId>,
    pub player_to_actor_id: HashMap<PlayerId, boxcars::ActorId>,
    pub player_to_car: HashMap<boxcars::ActorId, boxcars::ActorId>,
    pub player_to_team: HashMap<boxcars::ActorId, boxcars::ActorId>,
    pub car_to_player: HashMap<boxcars::ActorId, boxcars::ActorId>,
    pub car_to_boost: HashMap<boxcars::ActorId, boxcars::ActorId>,
    pub car_to_jump: HashMap<boxcars::ActorId, boxcars::ActorId>,
    pub car_to_double_jump: HashMap<boxcars::ActorId, boxcars::ActorId>,
    pub car_to_dodge: HashMap<boxcars::ActorId, boxcars::ActorId>,
    pub boost_pad_events: Vec<BoostPadEvent>,
    pub(crate) current_frame_boost_pad_events: Vec<BoostPadEvent>,
    pub(crate) boost_pad_pickup_sequence_times: HashMap<(String, u8), f32>,
    pub touch_events: Vec<TouchEvent>,
    pub(crate) current_frame_touch_events: Vec<TouchEvent>,
    pub dodge_refreshed_events: Vec<DodgeRefreshedEvent>,
    pub(crate) current_frame_dodge_refreshed_events: Vec<DodgeRefreshedEvent>,
    pub(crate) dodge_refreshed_counters: HashMap<PlayerId, i32>,
    pub goal_events: Vec<GoalEvent>,
    pub(crate) current_frame_goal_events: Vec<GoalEvent>,
    pub player_stat_events: Vec<PlayerStatEvent>,
    pub(crate) current_frame_player_stat_events: Vec<PlayerStatEvent>,
    pub(crate) player_stat_counters: HashMap<(PlayerId, PlayerStatEventKind), i32>,
    pub demolishes: Vec<DemolishInfo>,
    pub(crate) known_demolishes: Vec<(DemolishAttribute, usize)>,
    pub(crate) demolish_format: Option<DemolishFormat>,
    pub(crate) kickoff_phase_active_last_frame: bool,
}
